##########################################
#####             MCSF               #####
#####        Author: Jochyoua        #####
##########################################

##### Variables
variables:
  prefix: "&6[MCSF]&f"
  noperm: "%prefix% You lack permission."
  toggle: "%prefix% The swear filter has been %value%" ## Value (enabled/disabled)
  targetToggle: "%prefix% %target%'s swear filter has been %value%" ## Target (Player's name) / Value (enabled/disabled)
  disabled: "%prefix% An administrator has disabled this function"
  status: "%prefix% %target%'s swear filter is %value%" ## Target (Player's name) / Value (enabled/disabled)
  failure: "%prefix% &cFailure: %message%"
  success: "%prefix% &aSuccess: %message%"
  help:
    - "&6-------------------%prefix%&6-------------------------"
    - "&6* Command - Description"
    - "&6* /mcsf toggle [player] - Toggles the swear filter for yourself or someone else"
    - "&6* /mcsf status [player] - Views the status of a target's filter status"
    - "&6* /mcsf reload - Reload the server's configuration files"
    - "&6------------------------------------------------"
##### Settings
settings:
  default: false #Enable filter by default
  force: false #Force filter to enabled state
  log: true #Log toggle events for players
  replacement: "&c*&f"
  discordSRV: false #Support for plugin DiscordSRV
  mysql: false

##### Mysql
mysql:
  host: "localhost"
  username: "root"
  password: "foobar"
  database: "default"
  port: "3306"

##### User data
users:
  069a79f4-44e9-4726-a5be-fca90e38aaf5:
    enabled: true
    playername: Notch
##### Swear list
swears:
  - 2g1c
  - anal
  - anilingus
  - anus
  - apeshit
  - arsehole
  - asshole
  - assmunch
  - autoerotic
  - babeland
  - bangbros
  - bareback
  - barenaked
  - bastard
  - bastardo
  - bastinado
  - beaner
  - beaners
  - bestiality
  - bimbos
  - birdlock
  - bitch
  - blowjob
  - blumpkin
  - bollocks
  - bondage
  - boner
  - boob
  - boobs
  - bukkake
  - bulldyke
  - bullshit
  - bunghole
  - busty
  - buttcheeks
  - butthole
  - camgirl
  - camslut
  - camwhore
  - carpetmuncher
  - circlejerk
  - clitoris
  - clusterfuck
  - cock
  - cocks
  - coprolagnia
  - coprophilia
  - cornhole
  - coon
  - coons
  - creampie
  - cumming
  - cunnilingus
  - cunt
  - darkie
  - daterape
  - deepthroat
  - dendrophilia
  - dildo
  - dingleberry
  - dingleberries
  - dirty pillows
  - dirty sanchez
  - doggiestyle
  - doggystyle
  - dolcett
  - domination
  - dominatrix
  - dommes
  - ecchi
  - ejaculation
  - erotic
  - erotism
  - escort
  - eunuch
  - faggot
  - fecal
  - fellatio
  - feltch
  - femdom
  - figging
  - fingerbang
  - fingering
  - fisting
  - foot fetish
  - footjob
  - frotting
  - fuck
  - fudge packer
  - fudgepacker
  - futanari
  - genitals
  - goatcx
  - goatse
  - gokkun
  - goodpoop
  - goregasm
  - grope
  - g-spot
  - gspot
  - handjob
  - hardcore
  - hentai
  - homoerotic
  - honkey
  - hooker
  - humping
  - incest
  - intercourse
  - jailbait
  - jizz
  - juggs
  - kike
  - kinbaku
  - kinkster
  - kinky
  - knobbing
  - lolita
  - lovemaking
  - masturbate
  - milf
  - motherfucker
  - muffdiving
  - nambla
  - nawashi
  - negro
  - neonazi
  - nigga
  - nigger
  - nimphomania
  - nipple
  - nipples
  - nude
  - nudity
  - nympho
  - nymphomania
  - octopussy
  - omorashi
  - orgasm
  - orgy
  - paedophile
  - paki
  - pakistan
  - panties
  - panty
  - pedobear
  - pedophile
  - pegging
  - penis
  - pissing
  - pisspig
  - playboy
  - ponyplay
  - poontang
  - punany
  - poopchute
  - porn
  - porno
  - pornography
  - pubes
  - pussy
  - queaf
  - queef
  - quim
  - raghead
  - raping
  - rapist
  - rectum
  - rimjob
  - rimming
  - sadism
  - santorum
  - schlong
  - scissoring
  - semen
  - shemale
  - shibari
  - shit
  - shota
  - shrimping
  - skeet
  - slanteye
  - slut
  - s&m
  - smut
  - snatch
  - snowballing
  - sodomize
  - sodomy
  - splooge
  - spooge
  - spunk
  - strapon
  - strappado
  - suck
  - swastika
  - swinger
  - threesome
  - throating
  - tits
  - titty
  - topless
  - tosser
  - towelhead
  - tranny
  - tribadism
  - tubgirl
  - tushy
  - twat
  - twink
  - twinkie
  - undressing
  - upskirt
  - urophilia
  - vagina
  - vibrator
  - vorarephilia
  - voyeur
  - vulva
  - wank
  - wetback
  - yaoi
  - yiffy
  - zoophilia
