settings:
  # What language would you like to be used?
  # Acceptable languages are
  # en_us (English), fr_fr (French), es_es (Spanish), de_de (German)
  language: en_us

  # Would you like extra information to be shown on console?
  # Despite the value, all debug messages are saved in /data/debug.txt
  debug: false

  # Would you like some information on enable? It shows swear count, plugin/server version, etc
  console motd: true

  # Cool down for all MCSF commands, ignored if the player has the Permission MCSF.bypass
  # Default value is 5, to disable set to 0 (Integer)
  cooldown: 5

  # Enable support for placeholderAPI values in the messages sent to player
  # Only messages issued by players will contain placeholderAPI messages, console will receieve the raw placeholder message.
  enable placeholder api: true

  # Would you like to be notified on plugin updates?
  # "updating.update notification ingame" will notify users with the permission MCSF.update
  updating:
    check for updates: true
    update notification ingame: true

  filtering:
    # What should the player's default filtering status be?
    # If this value is false, all newly generated players will have their filter disabled.
    default: false

    # Would you like messages to be filtered twice?
    # This will prevent users from bypassing the filter by doing this: shi **** t
    double filtering: false

    # Should the filter be on for every player no matter what?
    force: false

    # Should strings in /data/global.yml be used and filtered for all players?
    global blacklist:
      enabled: true

    # Should message containing flagged strings be saved to config?
    save messages:
      enabled: true
    # Should filter changes be logged into console?
    log filter changes: true

    # Enable the above if you plan on whitelisting words
    whitelist words: false

    # Enable this if you plan on replacing words with another word, see replacements
    replace word for word: false

    # Enable this if you want to filter the reverse instance of a word: E.G kcuf (fuck) would be filtered
    filter reverse versions of swears: true

    # Basic replacement, repeats for each letter in the blacklisted word so E.G fuck would be ****
    replacement: "&c*&r"

    # Do you want messages with special characters to be filtered?
    # If this is disabled, the string f_u_c_k will not be filtered.
    ignore special characters:
      enabled: true
      characters to ignore: "!@#$%^&*()_+-"

    # Punishments for being flagged by the filter
    # Only player actions can flag this, such as chatting or writing in books and having any word contain something that's filtered.
    punishments:
      punish players: false
      punish check:
        books: true
        chat: true
      flags:
        reset every interval at: 10
      commands:
        # '1': This is the amount of flags that is needed for a player to be punished with this command
        #   commands: This is the command(s) that will be executed if a player were to be caught by this feature
        #   execute_as: This is who will execute the command, if the value is CONSOLE, the CONSOLE will execute,
        #   any other value will be treated as a player executing the command
        '1':
          commands:
            - 'tell {PLAYER} Swearing isn''t allowed. Swear again and you will be kicked.'
          execute_as: "CONSOLE"
        '2':
          commands:
            - 'kick {PLAYER} Swearing isn''t allowed on this server!'
          execute_as: "CONSOLE"

    # Filter checks
    # bookcheck: this checks books for swears and filters them accordingly
    filter checks:
      bookcheck: true

  # Do you want to only filter players?
  # enabled: enables this feature
  # log chat messages: logs the messages that are flagged by the filter
  # remove message on swear: removes the message if the swear contains something filtered
  only filter players:
    enabled: false
    log chat messages: true
    remove message on swear: false

  # This enables discordSRV functionality
  # enabled: enables this feature
  discordSRV:
    enabled: false

    # Should special characters be escaped?
    # escape swears: Should special characters only be escaped for swears?
    # escape entire message: Should special characters be escaped before sending the cleaned message to the Discord server? Can't be enabled in correlation with escape swears
    escape special chars:
      escape swears: true
      escape entire message: false

    # Should messages be contained in spoilers?
    # enabled: enables this feature
    # template: template for swear replacement, E.G ||{swear}|| would show up as ||fuck|| if the message contained the word fuck
    spoilers:
      enabled: false
      template: "||{swear}||"

  # Command arguments manager
  # Use this to disable certain commands from being executed by anyone.
  command args enabled:
    version: true
    add: true
    whitelist: true
    status: true
    remove: true
    reset: true
    help: true
    toggle: true
    unset: true

# Custom replacement messages
# all: default value, if no word is here the message will be replaced with *
# fuck: default value, if fuck is a flagged word in a message, it will be replaced with "&cReally bad word!"
replacements:
  all: "&c*&f"
  fuck: "&cReally bad word!"
swearcount: 0