##### Settings
settings:
  default: false #Enable filter by default
  language: en_us
  force: false #Force filter to enabled state
  log: true #Log toggle events for players
  debug: false # If you want the nasty console spam
  console_motd: true # If you want some information on plugin startup :)
  check_for_updates: true # Whether to check for updates or not
  update_notification_ingame: true # Whether or not to notify admins onjoin about updates
  replace_word_for_word: false # Replace each word with another, predefined word.
  cooldown: 5 # Set this to 0 If you wish to disable. Follows seconds and is an Integer
  replacement: "&c*&r" # What to replace blacklisted words with E.G: fuck = ****
  discordSRV: false #Support for plugin DiscordSRV
  mysql: false # Whether or not to use mysql
  bookcheck: true #Book check allows the server to filter out swears inside of Books.
  signcheck: false #Sign check allows the server to filter out swears inside of signs, could cause lag.
  punish_players: false # Punish players if they swear!
  remove_message_on_swear: false # Removes messages that contain swears, only works for players!
  only_filter_players: false #Only filter player chat, useful if you want server messages to remain unfiltered
  punish_check:
    books: true
    signs: true
    chat: true
  command_args_enabled:
    version: true
    add: true
    status: true
    remove: true
    reset: true
    reload: true
    help: true
    toggle: true
    unset: true

custom_regex:
  enabled: false
  regex:
    - '\b(?:(?:2(?:[0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9])(\.|,|-)){3}(?:(?:2([0-4][0-9]|5[0-5])|[0-1]?[0-9]?[0-9]))\b {TYPE=PLAYERS, BOOKS, SIGNS}'
    - '\b[^\sw\.@/]([0-9a-zA-Z\-\.]*[0-9a-zA-Z\-]+\.)(?i)(de|com|org|net|edu|land|co\.uk)\b {TYPE=PLAYERS, BOOKS, SIGNS}'
##### Mysql
mysql:
  host: "localhost"
  username: "root"
  password: "foobar"
  database: "default"
  port: "3306"
  use_unicode: true
  connection: "jdbc:mysql://{host}:{port}/{database}?useUnicode={unicode}&characterEncoding=utf8&autoReconnect=true&useSSL={ssl}"
  ssl: false
##### User data
users:
  069a79f4-44e9-4726-a5be-fca90e38aaf5:
    enabled: true
    playername: Notch
##### Replace word for word
replacements:
  all: "&c*&f"
  fuck: "&cReally bad word!"
##### Swear list
swearcount: 0
swears:
  - 2g1c
  - anal
  - anilingus
  - apeshit
  - arsehole
  - asshole
  - assmunch
  - autoerotic
  - babeland
  - bangbros
  - bareback
  - barenaked
  - bastard
  - bastardo
  - bastinado
  - beaner
  - beaners
  - bestiality
  - bimbos
  - birdlock
  - bitch
  - blowjob
  - blumpkin
  - bollocks
  - bondage
  - boner
  - boob
  - boobs
  - bukkake
  - bulldyke
  - bullshit
  - bunghole
  - busty
  - buttcheeks
  - butthole
  - camgirl
  - camslut
  - camwhore
  - carpetmuncher
  - circlejerk
  - clitoris
  - clusterfuck
  - cock
  - cocks
  - coprolagnia
  - coprophilia
  - cornhole
  - coon
  - coons
  - creampie
  - cumming
  - cunnilingus
  - cunt
  - darkie
  - daterape
  - deepthroat
  - dendrophilia
  - dildo
  - dingleberry
  - dingleberries
  - dirtypillows
  - dirtysanchez
  - doggiestyle
  - doggystyle
  - dolcett
  - domination
  - dominatrix
  - dommes
  - ecchi
  - ejaculation
  - erotic
  - erotism
  - escort
  - eunuch
  - faggot
  - fecal
  - fellatio
  - feltch
  - femdom
  - figging
  - fingerbang
  - fingering
  - fisting
  - foot fetish
  - footjob
  - frotting
  - fuck
  - fudgepacker
  - futanari
  - genitals
  - goatcx
  - goatse
  - gokkun
  - goodpoop
  - goregasm
  - grope
  - g-spot
  - gspot
  - handjob
  - hardcore
  - hentai
  - homoerotic
  - honkey
  - hooker
  - humping
  - incest
  - intercourse
  - jailbait
  - jizz
  - juggs
  - kike
  - kinbaku
  - kinkster
  - kinky
  - knobbing
  - lolita
  - lovemaking
  - masturbate
  - milf
  - motherfucker
  - muffdiving
  - nambla
  - nawashi
  - negro
  - neonazi
  - nigga
  - nigger
  - nimphomania
  - nipple
  - nipples
  - nude
  - nudity
  - nympho
  - nymphomania
  - octopussy
  - omorashi
  - orgasm
  - orgy
  - paedophile
  - paki
  - pakistan
  - panties
  - panty
  - pedobear
  - pedophile
  - pegging
  - penis
  - pissing
  - pisspig
  - playboy
  - ponyplay
  - poontang
  - punany
  - poopchute
  - porn
  - porno
  - pornography
  - pubes
  - pussy
  - queaf
  - queef
  - quim
  - raghead
  - raping
  - rapist
  - rectum
  - rimjob
  - rimming
  - sadism
  - santorum
  - schlong
  - scissoring
  - semen
  - shemale
  - shibari
  - shit
  - shota
  - shrimping
  - skeet
  - slanteye
  - slut
  - s&m
  - smut
  - snatch
  - snowballing
  - sodomize
  - sodomy
  - splooge
  - spooge
  - spunk
  - strapon
  - strappado
  - suck
  - swastika
  - swinger
  - threesome
  - throating
  - tits
  - titty
  - topless
  - tosser
  - towelhead
  - tranny
  - tribadism
  - tubgirl
  - tushy
  - twat
  - twink
  - twinkie
  - undressing
  - upskirt
  - urophilia
  - vagina
  - vibrator
  - vorarephilia
  - voyeur
  - vulva
  - wank
  - wetback
  - yaoi
  - yiffy
  - zoophilia