name: MCSF
main: com.github.Jochyoua.MCSF.Main
version: 3.2
description: simple toggleable swear filter
authors: [Jochyoua]
depend:
  - ProtocolLib
softdepend:
  - DiscordSRV
  - MySQL
api-version: 1.15
commands:
  mcsf:
    description: Main command for MCSF
permissions:
  MCSF.*:
    description: Gives access to all MCSF commands
    children:
      MCSF.modify: true
      MCSF.toggle: true
  MCSF.modify:
    description: Gives the player the ability to modify the blacklist
    default: false
  MCSF.toggle:
    description: Allows the player to enable/disable the swear filter
    default: true
  MCSF.version:
    description: Permission for the version command
    default: true